name: Run ProfitableCPMRate Script

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Updated to v4

      - name: Set Up Python
        uses: actions/setup-python@v4  # Already using v4, but ensure it's correct
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests matplotlib aiohttp

      - name: Run Script
        run: |
          python proxy.py

      - name: Upload Metrics Report
        uses: actions/upload-artifact@v3
        with:
          name: Metrics Report
          path: metrics_report.md

      - name: Upload Metrics Graph
        uses: actions/upload-artifact@v3
        with:
          name: Metrics Graph
          path: metrics_graph.png
